@startuml
title "MyNotes Application - Activity Diagram (All Execution Flows)"

start
:A;
:B;

if (X?) then (Y)
  :C;

  while (Z) is (FF)
    if (GGG) then (D)
      :E;
      :F;
      :G;
      :H;
      :I;
      :J;
      :K;

    elseif (L)
      :M;
      :N;
      :O;
      :P;
      :Q;
      :T;
      :R;
      if (U?) then (V)
      :W;
      else (X)
      :Y;
      endif
      :Z;

    elseif (DD)
      :EE;
      :II;
      :JJ;
      :KK;

    elseif (NN)
      :OO;
      :PP;
      :QQ;

    endif
  endwhile (RR)

else (SS)
  :TT;
  :UU;
  :VV;

  if (WW?) then (XX)
    :YY;
    :ZZ;
    :AAA;
  else (BBB)
    :CCC;
    :DDD;
  endif

endif

:EEE;
stop

@enduml

